### Python for Data Science

welcome to my Python for DS, Wi'll learn about the most popular Python libraries used in Data Science: Numpy, Pandas and Matplotlib.

Python is the #1 programming language for DS and for good reason:

- Python is easy to learn

- the syntax is easy to read and understand

- there are many usefull libraries to perform computations and other operations

Data Science user various tehniques and methods to extract knowledge and insight from data. let's dive into some basic of statistics first. 

mean: the average of the values

median: the middle value

Standart Deviation: the measure of spread.

### Numpy

NumPy (Numerical Python) is a Python library used to work with numerical data.
NumPy includes functions and data structures that can perform a wide variety of mathematical operations.

To start using NumPy, we first need to import it:

In [1]:
import numpy as np

In Python, lists are used to store data.
NumPy provides an array structure for performing operations with data.
NumPy arrays are faster and more compact than lists.

A NumPy array can be created using the np.array() function, providing it a list as the argument:

In [2]:
x = np.array([1,2,3,4])

Now, x is a NumPy array containing 4 values.
We can access its elements using their indexes, which start from 0:

In [3]:
print(x[0])

1


NumPy arrays are homogeneous, meaning they can contain only a single data type, while lists can contain multiple different types of data.

### Numpy Arrays

NumPy arrays are often called ndarrays, which stands for "N-dimensional array", because they can have multiple dimensions.

In [4]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x[1][2])

6


This will create a 2-dimensional array, which has 3 columns and 3 rows, and output the value at the 2nd row and 3rd column.

Arrays have properties, which can be accessed using a dot.
ndim returns the number of dimensions of the array.
size returns the total number of elements of the array.
shape returns a tuple of integers that indicate the number of elements stored along each dimension of the array.

For example:

In [5]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
print(x.ndim) # 2
print(x.size) # 9
print(x.shape) # (3, 3)

2
9
(3, 3)


So, the array in our example has 2 dimensions, 9 elements and is a 3x3 matrix (3 rows and 3 columns).

We can add, remove and sort an array using the np.append(), np.delete() and np.sort() functions.

In [6]:
import numpy as np

x = np.array([2, 1, 3])

x = np.append(x, 4)
x = np.delete(x, 0)
x = np.sort(x)

print(x)

[1 3 4]


np.arange() allows you to create an array that contains a range of evenly spaced intervals (similar to a Python range):

In [7]:
import numpy as np

x = np.arange(2, 10, 3)
print(x)

[2 5 8]


In [8]:
x = np.arange(2, 8, 2)
x = np.append(x, x.size)
x = np.sort(x)
print(x[1])
3


3


3

### Reshape

Recall that shape refers to the number of rows and columns in the array.

For example, let's consider the following array:

In [9]:
import numpy as np

x = np.arange(1, 7)
 
print(x)

[1 2 3 4 5 6]


This is a 1-dimensional array, containing 6 elements.

NumPy allows us to change the shape of our arrays using the reshape() function. For example, we can change our 1-dimensional array to an array with 3 rows and 2 columns:

In [10]:
import numpy as np

x = np.arange(1, 7)

z = x.reshape(3, 2)

print(z)

[[1 2]
 [3 4]
 [5 6]]


When you use the reshape method, the array you want to produce needs to have the same number of elements as the original array.

Reshape can also do the opposite: take a 2-dimensional array and make a 1-dimensional array from it:

In [11]:
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6]])

z = x.reshape(6)

print(z)

[1 2 3 4 5 6]


The result is a flat array that contains 6 elements.

The same result can be achieved using the flatten() function.

In [12]:
x = np.arange(1, 8, 3)
z = x.reshape(3, 1)
print(z[1][0])


4


### Indexing and Slicing

NumPy arrays can be indexed and sliced the same way that Python lists are.

For example:

In [13]:
import numpy as np

x = np.arange(1, 10)

print(x[0:2])
print(x[5:])
print(x[:2])
print(x[-3:])

[1 2]
[6 7 8 9]
[1 2]
[7 8 9]


Negative indexes count from the end of the array, so, [-3:] will result in the last 3 elements.

### Conditions

You can provide a condition as the index to select the elements that fulfill the given condition.

For example, let's select the elements that are less than 4:

In [14]:
import numpy as np

x = np.arange(1, 10)

print(x[x<4])

[1 2 3]


Conditions can be combined using the & (and) and | (or) operators.
For example, let's take the even numbers that are greater than 5:

In [15]:
import numpy as np

x = np.arange(1, 10)

print(x[(x>5) & (x%2==0)])

[6 8]


The condition can also be assigned to a variable, which will be an array of boolean values showing whether or not the values in the array fulfill the condition:
y = (x>5) & (x%2==0)

### Operations

It is easy to perform basic mathematical operations with arrays.
For example, to find the sum of all elements, we use the sum() function:

In [16]:
import numpy as np

x = np.arange(1, 10)

print(x.sum())

45


In [19]:
data_mb = np.array([6, 3, 10, 143])

data_kb = data_mb * 1024

print(data_kb.max())


146432


Similarly, min() and max() can be used to get the smallest and largest elements.

We can also perform operations between the array and a single number.
For example, we can multiply all elements by 2:


In [17]:
import numpy as np

x = np.arange(1, 10)
y = x*2

print(y)

[ 2  4  6  8 10 12 14 16 18]


As simple as that! Take your array and perform any operation you want with it!

### Statistics

Remember the summary statistics we learned in the previous module? Those included mean, median, variance and standard deviation.

NumPy arrays have built-in functions to return those values.

In [18]:
import numpy as np

x = np.array([14, 18, 19, 24, 26, 33, 42, 55, 67])

print(np.mean(x))
print(np.median(x))
print(np.var(x))
print(np.std(x))

33.111111111111114
26.0
292.5432098765432
17.10389458212787


As you can see, NumPy provides many useful functions to perform common operations with arrays.

In [20]:
x = np.arange(3, 9)
z = x.reshape(2, 3)
print(z[1][1])

7


In [21]:
# Fill in the blanks to select the elements of 'x' that are larger than the mean.
x[x>np.mean(x)]

array([6, 7, 8])

In [22]:
x = np.arange(1, 5)
x = x*2
print(x[:3].sum())

12


In [23]:
import numpy as np

data = np.array([1000, 2500, 1400, 1800, 900, 4200, 2200, 1900, 3500])

new_house = int(input())
data = np.append(data, new_house)
data = np.sort(data)
print(data)

KeyboardInterrupt: Interrupted by user

### 

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=cc67d05c-cf14-4b9c-9cf4-5fbefe179652' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>